<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRCnn09C\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRCnn09C/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRCnn09C.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRCnn09C\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRCnn09C\App_KernelDevDebugContainer([
    'container.build_hash' => 'RCnn09C',
    'container.build_id' => '4f09f5ba',
    'container.build_time' => 1730652935,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRCnn09C');
